### PR TITLE
Updated links for pytest, nose and unittest

### PR DESCRIPTION
**Pull request by kgashok**

### CODE REVIEW

**Comment by ChrisBarker-NOAA** [comment]
Thanks -- I'm going to wait a bit to see if you have more :-)

**Comment by kgashok** [comment]
No, that's it! Thank you for your concise and useful ideas!

**Comment by kgashok** [comment]
Just curious: did this PR get deployed?

**Comment by ChrisBarker-NOAA** [comment]
not yet -- I haven't gotten around to setting up the CI to auto-build it.

But it should be live now.

**Comment by kgashok** [comment]
If you just list down the various steps for deploying, I can test it out using `Github Workflow Actions`.
If it works, I will do a PR on that as well. Thanks,

**Comment by kgashok** [comment]
Can't believe I got it to work! 
https://kgashok.github.io/PythonTopics/where_to_put_tests.html#tl-drs (purposely placed a 's' after `tl;dr`)
- Used a much edited requirements.txt file 
- Used a stock Python build package to do the `make html`
- And then used the deploy package (available on Github) to push to gh-pages

**Comment by ChrisBarker-NOAA** [comment]
* Used a much edited requirements.txt file

much edited? what was needed?  should be pretty much only sphinx. but sure.

* Used a stock Python build package to do the make html

? you mean python with pip-installed sphinx?

* And then used the deploy package (available on Github) to push to gh-pages

great -- I hadn't gotten around to figureng that out.

Can you do a PR?

**Comment by kgashok** [comment]
Done!

**Pull request merged**
